# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yoga Belly
email: contact@yogabellystudio.com
description: > # Yoga
  Belly.
baseurl: "/yogabelly" # the subpath of your site, e.g. /blog
url: "http://ojensen5115.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

category-list: [classes, teachers]

# Navigation
navigation:
  -
    label: Home
    url: /index.html
  -
    label: Classes
    url: /classes/
  -
    label: Teachers
    url: /teachers/
  -
    label: Locations
    url: /locations/
  -
    label: Rates
    url: /rates/
  -
    label: FAQ
    url: /faq/
  -
    label: Schedule
    url: /schedule/
  -
    label: Workshops
    url: /workshops/
  -
    label: Contact Us
    url: /contact_us/
navigation_links:
  -
    label: Retreats
    url: http://clients.mindbodyonline.com/classic/ws?studioid=11869&amp;stype=-101&amp;sView=week&amp;sLoc=0
  -
    label: Blog
    url: http://www.yogabellystudio.com/blog/
  -
    label: Events
    url: https://clients.mindbodyonline.com/classic/ws?studioid=11869&amp;stype=-102&amp;sView=day&amp;date=06/13/15