# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yoga Belly
email: contact@yogabellystudio.com
description: > # Yoga
  Belly.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yogabelly.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Defines which types of things have their own listsings
category-list: [classes, teachers]

# Allows us to put the blog in a subdirectory
#permalink: /blog/:categories/:year/:month/:day/:title.html
permalink: /blog/:year/:month/:day/:title.html

# How many posts per page would you like to see on the blog?
paginate: 10

# What should the URLs of blog pages look like?
paginate_path: "/blog/page:num/"

# Dependencies... ignore this line
gems: [jekyll-paginate]
